# This should be used to set up an 
# environment with this. 
services:
  db:
    restart: always
    image: postgres
    container_name: template_app_pg
    environment:
      - POSTGRES_USER=template_app_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=template_app_database
      - POSTGRES_CONNECTION_TIMEOUT=600
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: 'bitnami/redis:latest'
    restart: always
    container_name: template_app_cache
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
    volumes:
      - redis-data:/data

  web: 
    restart: always
    image: ghcr.io/adamkali/template_app:${GIT_COMMIT_HASH:-latest}
    container_name: template_app_web
    ports:
      - '15150:5150'
    environment: 
      - JWT_PASSWORD=${JWT_PASSWORD}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
      - REDIS_URL="http://127.0.0.1:6379"
    deploy:
      update_config:
        order: start-first
    depends_on:
      - db
    
volumes:
  redis-data:
  pgadmin-data:
  pg-data:
