services:
  web:
    build:
      context: .
      dockerfile: dockerfile 
    container_name: template_app_web
    ports:
      - '5150:5150'
    environment: 
      - POSTGRES_URI=${POSTGRES_URI}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URI=${REDIS_URI}
