# This should be used to set up an 
# environment with this. 
services:
  db:
    restart: always
    image: postgres
    container_name: template_app_pg
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=template_app_user
      - POSTGRES_PASSWORD=SZUTwbnwDTJcd0Btw3DDS8u1tY8WNC0J
      - POSTGRES_DB=template_app_database
      - POSTGRES_CONNECTION_TIMEOUT=1200
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
        - host

  redis:
    image: 'bitnami/redis:latest'
    restart: always
    container_name: template_app_cache
    environment:
      - ALLOW_EMPTY_PASSWORD=true
    ports:
      - '5170:6379'
    volumes:
      - redis-data:/data
    networks:
        - host


volumes:
  redis-data:
  pg-data:

networks:
  host:
