/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI doc for template_app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrentResponse
 */
export interface CurrentResponse {
    /**
     * 
     * @type {string}
     * @memberof CurrentResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CurrentResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CurrentResponse
     */
    pid: string;
}

/**
 * Check if a given object implements the CurrentResponse interface.
 */
export function instanceOfCurrentResponse(value: object): value is CurrentResponse {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('pid' in value) || value['pid'] === undefined) return false;
    return true;
}

export function CurrentResponseFromJSON(json: any): CurrentResponse {
    return CurrentResponseFromJSONTyped(json, false);
}

export function CurrentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'],
        'pid': json['pid'],
    };
}

export function CurrentResponseToJSON(json: any): CurrentResponse {
    return CurrentResponseToJSONTyped(json, false);
}

export function CurrentResponseToJSONTyped(value?: CurrentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'name': value['name'],
        'pid': value['pid'],
    };
}

