/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI doc for template_app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetailedResponseLoginResponseData
 */
export interface DetailedResponseLoginResponseData {
    /**
     * 
     * @type {boolean}
     * @memberof DetailedResponseLoginResponseData
     */
    isVerified: boolean;
    /**
     * 
     * @type {string}
     * @memberof DetailedResponseLoginResponseData
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DetailedResponseLoginResponseData
     */
    pid: string;
    /**
     * 
     * @type {string}
     * @memberof DetailedResponseLoginResponseData
     */
    token: string;
}

/**
 * Check if a given object implements the DetailedResponseLoginResponseData interface.
 */
export function instanceOfDetailedResponseLoginResponseData(value: object): value is DetailedResponseLoginResponseData {
    if (!('isVerified' in value) || value['isVerified'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('pid' in value) || value['pid'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function DetailedResponseLoginResponseDataFromJSON(json: any): DetailedResponseLoginResponseData {
    return DetailedResponseLoginResponseDataFromJSONTyped(json, false);
}

export function DetailedResponseLoginResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedResponseLoginResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'isVerified': json['is_verified'],
        'name': json['name'],
        'pid': json['pid'],
        'token': json['token'],
    };
}

export function DetailedResponseLoginResponseDataToJSON(json: any): DetailedResponseLoginResponseData {
    return DetailedResponseLoginResponseDataToJSONTyped(json, false);
}

export function DetailedResponseLoginResponseDataToJSONTyped(value?: DetailedResponseLoginResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_verified': value['isVerified'],
        'name': value['name'],
        'pid': value['pid'],
        'token': value['token'],
    };
}

