/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI doc for template_app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DetailedResponseCurrentResponseData } from './DetailedResponseCurrentResponseData';
import {
    DetailedResponseCurrentResponseDataFromJSON,
    DetailedResponseCurrentResponseDataFromJSONTyped,
    DetailedResponseCurrentResponseDataToJSON,
    DetailedResponseCurrentResponseDataToJSONTyped,
} from './DetailedResponseCurrentResponseData';

/**
 * 
 * @export
 * @interface DetailedResponseCurrentResponse
 */
export interface DetailedResponseCurrentResponse {
    /**
     * 
     * @type {DetailedResponseCurrentResponseData}
     * @memberof DetailedResponseCurrentResponse
     */
    data?: DetailedResponseCurrentResponseData;
    /**
     * 
     * @type {string}
     * @memberof DetailedResponseCurrentResponse
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailedResponseCurrentResponse
     */
    nextLink?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DetailedResponseCurrentResponse
     */
    successful: boolean;
}

/**
 * Check if a given object implements the DetailedResponseCurrentResponse interface.
 */
export function instanceOfDetailedResponseCurrentResponse(value: object): value is DetailedResponseCurrentResponse {
    if (!('successful' in value) || value['successful'] === undefined) return false;
    return true;
}

export function DetailedResponseCurrentResponseFromJSON(json: any): DetailedResponseCurrentResponse {
    return DetailedResponseCurrentResponseFromJSONTyped(json, false);
}

export function DetailedResponseCurrentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedResponseCurrentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : DetailedResponseCurrentResponseDataFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'nextLink': json['next_link'] == null ? undefined : json['next_link'],
        'successful': json['successful'],
    };
}

export function DetailedResponseCurrentResponseToJSON(json: any): DetailedResponseCurrentResponse {
    return DetailedResponseCurrentResponseToJSONTyped(json, false);
}

export function DetailedResponseCurrentResponseToJSONTyped(value?: DetailedResponseCurrentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DetailedResponseCurrentResponseDataToJSON(value['data']),
        'message': value['message'],
        'next_link': value['nextLink'],
        'successful': value['successful'],
    };
}

