/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI doc for template_app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetailedResponseCurrentResponseData
 */
export interface DetailedResponseCurrentResponseData {
    /**
     * 
     * @type {string}
     * @memberof DetailedResponseCurrentResponseData
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof DetailedResponseCurrentResponseData
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DetailedResponseCurrentResponseData
     */
    pid: string;
}

/**
 * Check if a given object implements the DetailedResponseCurrentResponseData interface.
 */
export function instanceOfDetailedResponseCurrentResponseData(value: object): value is DetailedResponseCurrentResponseData {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('pid' in value) || value['pid'] === undefined) return false;
    return true;
}

export function DetailedResponseCurrentResponseDataFromJSON(json: any): DetailedResponseCurrentResponseData {
    return DetailedResponseCurrentResponseDataFromJSONTyped(json, false);
}

export function DetailedResponseCurrentResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedResponseCurrentResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'],
        'pid': json['pid'],
    };
}

export function DetailedResponseCurrentResponseDataToJSON(json: any): DetailedResponseCurrentResponseData {
    return DetailedResponseCurrentResponseDataToJSONTyped(json, false);
}

export function DetailedResponseCurrentResponseDataToJSONTyped(value?: DetailedResponseCurrentResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'name': value['name'],
        'pid': value['pid'],
    };
}

