/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI doc for template_app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetailedResponseString
 */
export interface DetailedResponseString {
    /**
     * 
     * @type {string}
     * @memberof DetailedResponseString
     */
    data?: string;
    /**
     * 
     * @type {string}
     * @memberof DetailedResponseString
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailedResponseString
     */
    nextLink?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DetailedResponseString
     */
    successful: boolean;
}

/**
 * Check if a given object implements the DetailedResponseString interface.
 */
export function instanceOfDetailedResponseString(value: object): value is DetailedResponseString {
    if (!('successful' in value) || value['successful'] === undefined) return false;
    return true;
}

export function DetailedResponseStringFromJSON(json: any): DetailedResponseString {
    return DetailedResponseStringFromJSONTyped(json, false);
}

export function DetailedResponseStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedResponseString {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
        'message': json['message'] == null ? undefined : json['message'],
        'nextLink': json['next_link'] == null ? undefined : json['next_link'],
        'successful': json['successful'],
    };
}

export function DetailedResponseStringToJSON(json: any): DetailedResponseString {
    return DetailedResponseStringToJSONTyped(json, false);
}

export function DetailedResponseStringToJSONTyped(value?: DetailedResponseString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'message': value['message'],
        'next_link': value['nextLink'],
        'successful': value['successful'],
    };
}

