/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI doc for template_app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrentResponse } from './CurrentResponse';
import {
    CurrentResponseFromJSON,
    CurrentResponseFromJSONTyped,
    CurrentResponseToJSON,
    CurrentResponseToJSONTyped,
} from './CurrentResponse';

/**
 * 
 * @export
 * @interface DetailedResponse
 */
export interface DetailedResponse {
    /**
     * 
     * @type {CurrentResponse}
     * @memberof DetailedResponse
     */
    data?: CurrentResponse | null;
    /**
     * 
     * @type {string}
     * @memberof DetailedResponse
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailedResponse
     */
    nextLink?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DetailedResponse
     */
    successful: boolean;
}

/**
 * Check if a given object implements the DetailedResponse interface.
 */
export function instanceOfDetailedResponse(value: object): value is DetailedResponse {
    if (!('successful' in value) || value['successful'] === undefined) return false;
    return true;
}

export function DetailedResponseFromJSON(json: any): DetailedResponse {
    return DetailedResponseFromJSONTyped(json, false);
}

export function DetailedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : CurrentResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'nextLink': json['next_link'] == null ? undefined : json['next_link'],
        'successful': json['successful'],
    };
}

export function DetailedResponseToJSON(json: any): DetailedResponse {
    return DetailedResponseToJSONTyped(json, false);
}

export function DetailedResponseToJSONTyped(value?: DetailedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CurrentResponseToJSON(value['data']),
        'message': value['message'],
        'next_link': value['nextLink'],
        'successful': value['successful'],
    };
}

