/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI doc for template_app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForgotParams
 */
export interface ForgotParams {
    /**
     * 
     * @type {string}
     * @memberof ForgotParams
     */
    email: string;
}

/**
 * Check if a given object implements the ForgotParams interface.
 */
export function instanceOfForgotParams(value: object): value is ForgotParams {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ForgotParamsFromJSON(json: any): ForgotParams {
    return ForgotParamsFromJSONTyped(json, false);
}

export function ForgotParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForgotParams {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ForgotParamsToJSON(json: any): ForgotParams {
    return ForgotParamsToJSONTyped(json, false);
}

export function ForgotParamsToJSONTyped(value?: ForgotParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

