/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI doc for template_app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginParams
 */
export interface LoginParams {
    /**
     * 
     * @type {string}
     * @memberof LoginParams
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LoginParams
     */
    password: string;
}

/**
 * Check if a given object implements the LoginParams interface.
 */
export function instanceOfLoginParams(value: object): value is LoginParams {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LoginParamsFromJSON(json: any): LoginParams {
    return LoginParamsFromJSONTyped(json, false);
}

export function LoginParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginParams {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function LoginParamsToJSON(json: any): LoginParams {
    return LoginParamsToJSONTyped(json, false);
}

export function LoginParamsToJSONTyped(value?: LoginParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

