/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI doc for template_app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponse
     */
    isVerified: boolean;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    pid: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    token: string;
}

/**
 * Check if a given object implements the LoginResponse interface.
 */
export function instanceOfLoginResponse(value: object): value is LoginResponse {
    if (!('isVerified' in value) || value['isVerified'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('pid' in value) || value['pid'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function LoginResponseFromJSON(json: any): LoginResponse {
    return LoginResponseFromJSONTyped(json, false);
}

export function LoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isVerified': json['is_verified'],
        'name': json['name'],
        'pid': json['pid'],
        'token': json['token'],
    };
}

export function LoginResponseToJSON(json: any): LoginResponse {
    return LoginResponseToJSONTyped(json, false);
}

export function LoginResponseToJSONTyped(value?: LoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_verified': value['isVerified'],
        'name': value['name'],
        'pid': value['pid'],
        'token': value['token'],
    };
}

