/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI doc for template_app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterParams
 */
export interface RegisterParams {
    /**
     * 
     * @type {string}
     * @memberof RegisterParams
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterParams
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterParams
     */
    password: string;
}

/**
 * Check if a given object implements the RegisterParams interface.
 */
export function instanceOfRegisterParams(value: object): value is RegisterParams {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function RegisterParamsFromJSON(json: any): RegisterParams {
    return RegisterParamsFromJSONTyped(json, false);
}

export function RegisterParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterParams {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'],
        'password': json['password'],
    };
}

export function RegisterParamsToJSON(json: any): RegisterParams {
    return RegisterParamsToJSONTyped(json, false);
}

export function RegisterParamsToJSONTyped(value?: RegisterParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'name': value['name'],
        'password': value['password'],
    };
}

