/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI doc for template_app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetParams
 */
export interface ResetParams {
    /**
     * 
     * @type {string}
     * @memberof ResetParams
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof ResetParams
     */
    token: string;
}

/**
 * Check if a given object implements the ResetParams interface.
 */
export function instanceOfResetParams(value: object): value is ResetParams {
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function ResetParamsFromJSON(json: any): ResetParams {
    return ResetParamsFromJSONTyped(json, false);
}

export function ResetParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetParams {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
        'token': json['token'],
    };
}

export function ResetParamsToJSON(json: any): ResetParams {
    return ResetParamsToJSONTyped(json, false);
}

export function ResetParamsToJSONTyped(value?: ResetParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'token': value['token'],
    };
}

