/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI doc for template_app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyParams
 */
export interface VerifyParams {
    /**
     * 
     * @type {string}
     * @memberof VerifyParams
     */
    token: string;
}

/**
 * Check if a given object implements the VerifyParams interface.
 */
export function instanceOfVerifyParams(value: object): value is VerifyParams {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function VerifyParamsFromJSON(json: any): VerifyParams {
    return VerifyParamsFromJSONTyped(json, false);
}

export function VerifyParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyParams {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function VerifyParamsToJSON(json: any): VerifyParams {
    return VerifyParamsToJSONTyped(json, false);
}

export function VerifyParamsToJSONTyped(value?: VerifyParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

