# Loco configuration file documentation

# Application logging configuration
logger:
  enable: true
  pretty_backtrace: true
  level: debug
  format: pretty

server:
  port: 5150
  host: http://localhost
  middlewares:
    static:
      enable: true
      must_exist: true
      precompressed: false
      folder:
        uri: "/"
        path: "frontend/dist"
      fallback: "frontend/dist/index.html"

workers:
  mode: BackgroundAsync

# Mailer Configuration.
mailer:
  smtp:
    enable: true
    host: {{ get_env(name="MAILER_HOST", default="localhost") }}
    port: 587
    secure: true
    auth: 
      user: {{ get_env(name="MAILER_USERNAME", default="admin") }}
      password: {{ get_env(name="MAILER_PASSWORD", default="admin") }}

database:
  # Database connection URI
  uri: 'postgres://postgres:yU3UUUEUL7wTnO19EAUhi6iQ7J1xIQR8G46ieMKQRaZVxEh25bCO4jedMWyowTmM@75.115.15.63:43544/postgres'
  enable_logging: true
  connect_timeout: {{ get_env(name="DB_CONNECT_TIMEOUT", default="100") }}
  idle_timeout: 50
  min_connections: 1
  max_connections: 3
  auto_migrate: true
  dangerously_truncate: false
  dangerously_recreate: false

# Queue Configuration
queue:
  kind: Redis
  uri: {{ get_env(name="REDIS_URL", default="redis://127.0.0.1") }}
  dangerously_flush: false

settings:
  minio_config:
    uri: 'https://minio-jwgcck0cs88k8cck0go08koc.kalilarosa.xyz'
    access_key: 3Jp09imRYd34bUQPWaVF,
    secret_key: rWGjZksQ0AYlpksHr53ZeSv6AL55EqFtCNViGC0z




# Authentication Configuration
auth:
  # JWT authentication
  jwt:
    # Secret key for token generation and verification
    secret: L1xnC3gHvyNktS8980yN
    # Token expiration time in seconds
    expiration: 604800 # 7 days
