logger:
  enable: true
  level: trace 
  format: compact

server:
  binding: 0.0.0.0
  port: 5150
  host: http://localhost
  middlewares:
    static:
      enable: true
      must_exist: true
      precompressed: false
      folder:
        uri: "/"
        path: "frontend/dist"
      fallback: "frontend/dist/index.html"

workers:
  mode: BackgroundAsync

mailer:
  smtp:
    enable: false
    host: smtp-mail.outlook.com
    port: 587
    secure: true
    auth: 
      user: adamkali@outlook.com 
      password: {{ get_env(name="MAILER_PASSWORD", default="admin") }}

database:
  # Database connection URI
  uri: 'postgres://fo0k0gg0c04sg4s0gows8kks:5432/postgres?user=postgres&password=yU3UUUEUL7wTnO19EAUhi6iQ7J1xIQR8G46ieMKQRaZVxEh25bCO4jedMWyowTmM'
  enable_logging: true
  connect_timeout: 500
  idle_timeout: 500
  min_connections: 1
  max_connections: 3
  auto_migrate: true
  dangerously_truncate: false
  dangerously_recreate: false

# Queue Configuration
queue:
  kind: Redis
  uri: 'http://E0PE1FO3apRDB4MolgDN0a9an1X9hArD0g7bh3iyR4bbtE2maICZpMrJwrksL9TH@u4gckkso8cg8kwgg0w4kwoko:6379'
  dangerously_flush: false

# Authentication Configuration
auth:
  jwt:
    secret: x39kjNsffFfNj20AFbzF
    expiration: 604800 # 7 days
