logger:
  enable: true
  level: trace 
  format: compact

server:
  binding: 0.0.0.0
  port: 5150
  host: http://localhost
  middlewares:
    static:
      enable: true
      must_exist: true
      precompressed: false
      folder:
        uri: "/"
        path: "frontend/dist"
      fallback: "frontend/dist/index.html"

workers:
  mode: BackgroundAsync

mailer:
  smtp:
    enable: false
    host: smtp-mail.outlook.com
    port: 587
    secure: true
    auth: 
      user: adamkali@outlook.com 
      password: {{ get_env(name="MAILER_PASSWORD", default="admin") }}

database:
  # Database connection URI
  uri: postgres://{{ get_env(POSTGRES_USER) }}:{{ get_env(POSTGRES_PASSWORD) }}@{{ get_env(SERVICE_FQDN_POSTGRES) }}/{{ get_env(POSTGRES_DB) }}
  enable_logging: true
  connect_timeout: 500
  idle_timeout: 500
  min_connections: 1
  max_connections: 3
  auto_migrate: true
  dangerously_truncate: false
  dangerously_recreate: false

# Queue Configuration
queue:
  kind: Redis
  uri: '{{ get_env(REDIS_URI) }}'
  dangerously_flush: false

# Authentication Configuration
auth:
  jwt:
    secret: '{{ get_env(JWT_PHRASE) }}'
    expiration: 604800 # 7 days

settings:
  minio_config:
    uri: '{{ get_env(MINIO_URI) }}'
    access_key: '{{ get_env(MINIO_ACCESS_TOKEN) }}',
    secret_key: '{{ get_env(MINIO_SECRET_TOKEN) }}'
